SELECT A.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY, SUM(B.PRICE*S.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK AS B,
(
SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES
WHERE SALES_DATE LIKE "2022-01-%"
GROUP BY BOOK_ID
) AS S,
AUTHOR AS A
WHERE B.BOOK_ID = S.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY 1,3 DESC