SELECT AB.AUTHOR_ID, AB.AUTHOR_NAME, AB.CATEGORY, SUM(AB.PRICE*S.SALES) AS TOTAL_SALES
FROM (
    SELECT B.BOOK_ID, A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE
    FROM BOOK AS B, AUTHOR AS A
    WHERE B.AUTHOR_ID = A.AUTHOR_ID 
    ) AS AB, BOOK_SALES AS S
WHERE AB.BOOK_ID = S.BOOK_ID
AND YEAR(S.SALES_DATE)='2022' AND MONTH(S.SALES_DATE)='1'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC