-- 코드를 입력하세요
SELECT PRODUCT_CODE, (P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P, 
    (
        SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
        FROM OFFLINE_SALE
        GROUP BY PRODUCT_ID
    )AS O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY 2 DESC,1

