SELECT P.PRODUCT_CODE, P.PRICE*O.SA AS SALES
FROM PRODUCT AS P, 
(
SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SA
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID
) AS O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY P.PRICE*O.SA DESC, 1