-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
FROM
(
SELECT I.ANIMAL_ID, O.NAME, DATEDIFF(O.DATETIME, I.DATETIME)+1 AS DURATION
FROM ANIMAL_INS AS I, ANIMAL_OUTS AS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID
GROUP BY I.ANIMAL_ID
ORDER BY 3 DESC
LIMIT 2
) AS A