SELECT CH.CAR_ID, CH.CAR_TYPE, 
       TRUNCATE(CH.DAILY_FEE * ((100 - CAST(SUBSTRING_INDEX(P.DISCOUNT_RATE, "%", 1) AS UNSIGNED)) / 100) * 30, 0) AS FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    WHERE C.CAR_TYPE IN ("SUV", "세단")
      AND NOT EXISTS (
          SELECT 1
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
          WHERE C.CAR_ID = H.CAR_ID
            AND H.START_DATE <= "2022-11-30"
            AND H.END_DATE >= "2022-11-01"
      )
) AS CH
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON CH.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE = "30일 이상"
  AND CH.DAILY_FEE * ((100 - CAST(SUBSTRING_INDEX(P.DISCOUNT_RATE, "%", 1) AS UNSIGNED)) / 100) * 30 >= 500000
  AND CH.DAILY_FEE * ((100 - CAST(SUBSTRING_INDEX(P.DISCOUNT_RATE, "%", 1) AS UNSIGNED)) / 100) * 30 <= 2000000
ORDER BY FEE DESC, CH.CAR_TYPE, CH.CAR_ID DESC;
