-- 코드를 입력하세요

SELECT CP.CAR_ID, CP.CAR_TYPE, CP.FEE
FROM
(
SELECT C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE * ((100-P.DISCOUNT_RATE)/100) * 30),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C,
(
SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = "30일 이상"
) AS P
WHERE C.CAR_TYPE = P.CAR_TYPE AND (C.DAILY_FEE * ((100-P.DISCOUNT_RATE)/100) * 30 < 2000000)
) AS CP
WHERE CP.CAR_ID  NOT IN
(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01'
GROUP BY CAR_ID
)

ORDER BY 3 DESC, 2,1 DESC