-- 코드를 입력하세요
SELECT O.YEAR, O.MONTH, U.GENDER, COUNT(GENDER) AS 'USERS'
FROM USER_INFO AS U,
(
    SELECT YEAR(SALES_DATE) AS 'YEAR', MONTH(SALES_DATE) AS 'MONTH', USER_ID
    FROM ONLINE_SALE
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID
) AS O
WHERE U.USER_ID = O.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER