-- 코드를 입력하세요

SET @CC = (
    SELECT COUNT(USER_ID)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
    );
    
SELECT SI.YEAR , SI.MONTH, COUNT(SI.USER_ID) AS PUCHASED_USERS , ROUND(COUNT(SI.USER_ID)/@CC,1) AS PUCHASED_RATIO
FROM
(
    
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
FROM ONLINE_SALE AS O
WHERE USER_ID IN
(
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID
    
) AS SI
GROUP BY SI.YEAR, SI.MONTH
ORDER BY 1,2



