SELECT O.PRODUCT_ID, P.PRODUCT_NAME, O.TOTAL_AMOUNT*P.PRICE AS TOTAL_SALES
FROM
(
SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM FOOD_ORDER
WHERE PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
GROUP BY PRODUCT_ID
) AS O,
FOOD_PRODUCT AS P
WHERE O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY 3 DESC, 1