SELECT P.PRODUCT_ID, P.PRODUCT_NAME, O.AMOUNT * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
INNER JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT, PRODUCE_DATE
    FROM FOOD_ORDER AS O
    WHERE PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
    GROUP BY PRODUCT_ID
    ) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY 3 DESC, 1