-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P,
    (
    SELECT PRODUCT_ID, PRODUCE_DATE, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
    ) AS O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY 3 DESC,1