SELECT HP.HISTORY_ID, ROUND(C.DAILY_FEE*(100-HP.DISCOUNT_RATE)/100,0)*HP.DURATION AS FEE
FROM
(

SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DURATION, CASE
    WHEN DATEDIFF(END_DATE, START_DATE)+1 >=90 THEN 
    (
        SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = "트럭" AND DURATION_TYPE = "90일 이상"        
    )
    WHEN DATEDIFF(END_DATE, START_DATE)+1 >=30 THEN 
    (
        SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = "트럭" AND DURATION_TYPE = "30일 이상"        
    )
    WHEN DATEDIFF(END_DATE, START_DATE)+1 >=7 THEN 
    (
        SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = "트럭" AND DURATION_TYPE = "7일 이상"        
    )
    ELSE 0
    END
    AS DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE="트럭"
)
    
) AS HP,
CAR_RENTAL_COMPANY_CAR AS C
WHERE HP.CAR_ID = C.CAR_ID
ORDER BY 2 DESC, 1 DESC

