-- 코드를 입력하세요

SELECT CH.HISTORY_ID, 
    ROUND(CH.DAILY_FEE-(CH.DAILY_FEE*(IFNULL(DISCOUNT_RATE,0)/100)),0)*DURATION_DATE AS FEE
FROM
(
SELECT H.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE,
    (DATEDIFF(H.END_DATE,H.START_DATE)+1) AS DURATION_DATE,
    (
    CASE 
    WHEN (DATEDIFF(H.END_DATE,H.START_DATE)+1)>=90 THEN "90일 이상"
    WHEN (DATEDIFF(H.END_DATE,H.START_DATE)+1)>=30 THEN "30일 이상"
    WHEN (DATEDIFF(H.END_DATE,H.START_DATE)+1)>=7 THEN "7일 이상"
    ELSE NULL
    END) AS DURATION_TYPE
    
FROM CAR_RENTAL_COMPANY_CAR AS C, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = "트럭"
GROUP BY H.HISTORY_ID
) AS CH

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON CH.CAR_TYPE = P.CAR_TYPE AND CH.DURATION_TYPE = P.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC