-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM
(
SELECT PT_NO, MDDR_ID AS DR_ID , APNT_YMD, APNT_NO
FROM APPOINTMENT
WHERE MCDP_CD = "CS" AND APNT_CNCL_YN = "N" AND APNT_YMD LIKE "2022-04-13%"
) AS A
, PATIENT AS P, DOCTOR AS D
WHERE P.PT_NO = A.PT_NO AND A.DR_ID = D.DR_ID
ORDER BY 6