-- 코드를 입력하세요
SET @HOUR = -1;
SELECT (@HOUR := @HOUR+1) AS HOUR,
    (
        SELECT COUNT(ANIMAL_ID)
        FROM ANIMAL_OUTS
        WHERE(@HOUR = HOUR(DATETIME))
    )  AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23
GROUP BY HOUR
ORDER BY HOUR