SET @HOUR = -1;

SELECT (@HOUR := @HOUR +1) AS HOUR, IFNULL(C.COUNT,0) AS COUNT
FROM ANIMAL_OUTS AS H

LEFT JOIN 
(
SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
ORDER BY 1
) AS C
ON @HOUR+1 = C.HOUR
WHERE @HOUR<=22

