-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS P, REST_REVIEW AS R
WHERE P.MEMBER_ID = R.MEMBER_ID 
    AND R.MEMBER_ID =
    (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_ID)
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
    )
ORDER BY 3,2