-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B, BOOK_SALES AS S
WHERE B.BOOK_ID = S.BOOK_ID
AND YEAR(S.SALES_DATE)=2022 AND MONTH(S.SALES_DATE)=1
GROUP BY CATEGORY
ORDER BY CATEGORY